<h1><center>PYTHON BASICS</center></h1>

[Python](https://www.python.org/)<br>
[Docs](https://docs.python.org)<br>
[Python Developer's Guide](https://www.python.org/dev/)<br>
[Python Enhancement Proposals](https://www.python.org/dev/peps/)<br>
[PEP 8 – Style Guide for Python Code](https://peps.python.org/pep-0008/)


In [16]:
from platform import python_version
import sys
print('python_version: ',python_version())

python_version:  3.7.7


# OBJECTS in PYTHON

In [2]:
R1 = ['a', 'b']
print(R1)

['a', 'b']


In [3]:
r3 = R1
print(r3)

['a', 'b']


In [4]:
R1.append(10)
print(R1)

['a', 'b', 10]


In [5]:
print(r3)

['a', 'b', 10]


In [6]:
r3.append(20)
print(r3)

['a', 'b', 10, 20]


In [7]:
print(R1)

['a', 'b', 10, 20]


# SEQUENCES

In [8]:
#String
str = "abcd 123"
print(str[1])

b


In [9]:
str = "abcd 123"
str[1] = 9	#exception, immutable


TypeError: 'str' object does not support item assignment

In [10]:
#Tuple
Tuple_1 = (1, 'str', 2.3, (4,"a"))
print(Tuple_1)
print(Tuple_1[1])
print(Tuple_1[3])

(1, 'str', 2.3, (4, 'a'))
str
(4, 'a')


In [11]:
Tuple_1[1] = 'STR-STR' #exception, immutable


TypeError: 'tuple' object does not support item assignment

In [12]:
sngle = 'hello'
sngleTn = 'hello',            # <-- note trailing comma 
print(len(sngle))
print(len(sngleTn))

5
1


In [13]:
#Packing, unpacking
tuple_1 = 1111, 2222, 'hello!'  #packing
print(tuple_1)

x, y, z = tuple_1         #unpacking
print(x, y, z)

(1111, 2222, 'hello!')
1111 2222 hello!


In [10]:
#List
List_1 = [1, 'str', 2.3, (4,"a")]
print(List_1)
print(List_1[1])

[1, 'str', 2.3, (4, 'a')]
str


In [13]:
List_1[1] = 'STR-STR'
print(List_1)

[1, 'STR-STR', 2.3, (4, 'a')]


In [6]:
#List of Lists
dataBP = [[None]*4]*6

i = 0
print(dataBP)
dataBP[i][0] = 1
print(dataBP)
dataBP[i][1] = 0.1
print(dataBP)
dataBP[i][2] = 0.2
print(dataBP)

dataBP = [[None for j in range(4)] for i in range(6) ]

print()
i = 0
print(dataBP)
dataBP[i][0] = 1
print(dataBP)
dataBP[i][1] = 0.1
print(dataBP)
dataBP[i][2] = 0.2
print(dataBP)


[[None, None, None, None], [None, None, None, None], [None, None, None, None], [None, None, None, None], [None, None, None, None], [None, None, None, None]]
[[1, None, None, None], [1, None, None, None], [1, None, None, None], [1, None, None, None], [1, None, None, None], [1, None, None, None]]
[[1, 0.1, None, None], [1, 0.1, None, None], [1, 0.1, None, None], [1, 0.1, None, None], [1, 0.1, None, None], [1, 0.1, None, None]]
[[1, 0.1, 0.2, None], [1, 0.1, 0.2, None], [1, 0.1, 0.2, None], [1, 0.1, 0.2, None], [1, 0.1, 0.2, None], [1, 0.1, 0.2, None]]

[[None, None, None, None], [None, None, None, None], [None, None, None, None], [None, None, None, None], [None, None, None, None], [None, None, None, None]]
[[1, None, None, None], [None, None, None, None], [None, None, None, None], [None, None, None, None], [None, None, None, None], [None, None, None, None]]
[[1, 0.1, None, None], [None, None, None, None], [None, None, None, None], [None, None, None, None], [None, None, None, None], [None

In [14]:
#Dictionary
grade = {'0589': 80, '0510': 'S', 1: 100}
print(grade)

print(grade['0589'])
print(grade[1])
grade[1] = 85
print(grade)

{'0589': 80, '0510': 'S', 1: 100}
80
100
{'0589': 80, '0510': 'S', 1: 85}


In [15]:
#Set
set = {'r','d',1,'r','R'}
print(set)

{'r', 'd', 1, 'R'}


In [17]:
set1 = {1, 2, 3, 3, 3}
set2 = {3, 4, 5}
print("union: ",set1 | set2)
print("intersection: ",set1 & set2)
print("difference: ",set1 - set2)
print("difference: ",set2 - set1)
print("symmetric difference: ",set1 ^ set2)
print("symmetric difference: ",set1 - set2 | set2 - set1)


union:  {1, 2, 3, 4, 5}
intersection:  {3}
difference:  {1, 2}
difference:  {4, 5}
symmetric difference:  {1, 2, 4, 5}
symmetric difference:  {1, 2, 4, 5}


In [ ]:
set1 = {1, 2, 3, 3, 3}
set2 = {3, 4, 5}
print("symmetric difference: ",set1 ^ set2)

# MUTABLE & IMMUTABLE OBJECTS

## Immutable Objects

In [ ]:
#Immutable 
m = "Welcome"
print(m)

In [ ]:
m[0] = 'p'

In [ ]:
A = 'str1'
print('A1: ',A)
B = A
print('B1: ',B)

In [ ]:
B = 'str2'
print('A2: ',A)
print('B: ',B)

In [ ]:
B[0] = '1'

In [ ]:
x = 5.2
y = x
print("x= ", x,", y= ",y)

In [ ]:
y = 3.3
print("x= ", x,", y= ",y)

In [ ]:
y = x
print("x= ", x,", y= ",y)

In [ ]:
x = 2.3
print("x= ", x,", y= ",y)

## Mutable objects

In [ ]:
A = ["1", 2]
B = A
print('B: ', B)
B = 'str2'
print('A: ', A)
print('new B: ', B)

In [ ]:
C = A
print('C: ', C)

In [ ]:
C.append('cc')
print('new C: ', C)
print('A: ', A)

In [ ]:
C[0] = '2'
print('new C: ', C)
print('A: ', A)

In [ ]:
A[2] = 'aa'
print('C: ', C)
print('new A: ', A)

In [ ]:
grade = {'0589': 80, '0510': 'S', 1: 100}
print(grade)

In [ ]:
print(grade['0589'])

In [ ]:
print(grade[1])

In [ ]:
grade[1] = 85
print(grade[1])

# BRANCHING

In [18]:
x = int(input("Enter your number: "))

if x >= 10: 
    print('x is greater than 10')
elif x >= 5:
    print('x is greater than 5 and less than 10')
elif x >= 2:
    print('x is greater than 2 and less than 5')
else:
    print('‘x is less than 2')
#

Enter your number: 1
‘x is less than 2


In [ ]:
print(x, ' is greater than 10') if x > 10 else print(x, ' is NOT greater than 10')

# LOOPING

In [ ]:
choice = input("choose 1 or 2: ")

if choice == '1':
    myList = [11, 8, 4, 1, -1, 's']
else:
    myList = range(11,-1,-2)

print('\tchoice is ' + choice)
  
for x in myList:
    print('processing index of ' + str(myList.index(x)))    
  
    if x == 's':
        print("\tSTOP!")
        break
    #end if

    if x >= 10:
        print('\t' + str(x) + ' is greater than 10')
    elif x >= 5:
        print('\t' + str(x) + ' is greater than 5 and less than 10')
    elif x >= 2:
        print('\t' + str(x) + ' is greater than 2 and less than 5')
    else:
        print('\t' + str(x) + ' is less than 2')
    #end if
#end for

print("\n\n...END OF PROGRAM!")

In [ ]:
cont = True

while cont:
    number = input("Enter your number: ")

    if number == 's':
        cont = False
        print("STOP!")
        break
    #end if

    x = int(number)

    if x >= 10:
        print('x is greater than or equal to 10')
    elif x >= 5:
        print('x is greater than or equal to 5 and less than 10')
    elif x >= 2:
        print('x is greater than or equal to 2 and less than 5')
    else:
        print('x is less than 2')
    #end if
#end while

print("END OF PROGRAM")

# GENERATORS
[Generators](https://www.programiz.com/python-programming/generator)

In [1]:
my_list = [1, 3, 6, 10]

#Python Generator Expression
a = [x**2 for x in my_list]
print("a: ",a)

b = (x**2 for x in my_list)
print("b: ",b)

try:
    print("a[:]: ",a[:])
    print("b[:]: ",b[:])
except:
    print(':(')

a:  [1, 9, 36, 100]
b:  <generator object <genexpr> at 0x00000251FC5C1CF0>
a[:]:  [1, 9, 36, 100]
:(


In [2]:
my_list = [1, 3, 6, 10]
a = [0]*len(my_list)
print(a)
i = -1
for x in my_list:
    i = i+1
    a[i] = x
#
print(a)

[0, 0, 0, 0]
[1, 3, 6, 10]


In [3]:
mySet = {x for x in 'abracadabra' if x not in 'abc'}
print("mySet: ", mySet)
try:
    print("mySet[:] :",mySet[:])
except:
    print(':(')
#    

mySet:  {'d', 'r'}
:(


In [4]:
myTuple = (x for x in 'abracadabra' if x not in 'abc')
print("myTuple: ",myTuple)
try:
    print("myTuple[:] :",myTuple[:])
except:
    print(':(')
#    

myTuple:  <generator object <genexpr> at 0x000001D20F24FD48>
:(


## Pipelining Generators

In [2]:
with open('TestData.csv') as file:
    pizza_col = [line[3] for line in file]
    print(pizza_col)
    per_hour = (int(x) for x in pizza_col if x != 'N')
    print(per_hour)
    print("Total hours worked sold = ",sum(per_hour))

['2', '1', '3']
<generator object <genexpr> at 0x00000251FC5C1E40>
Total hours worked sold =  6


# ITERATION

In [6]:
v1 = (1,2,-1)
v2 = (-1,2,1)
dp=0
for i,k in enumerate(v1):
    dp += v2[i]*k #v1[i]*v2[i]
    print("i, k, dp: ",i,k,dp)
#
print("dp= ",dp)

i, k, dp:  0 1 -1
i, k, dp:  1 2 3
i, k, dp:  2 -1 2
dp=  2


In [7]:
v1 = (1,2,-1)
v2 = (-1,2,1)
print("v1: ",v1)

dp=0
for x in zip(v1,v2):
    dp += x[0]*x[1]
    print("x, dp : ",x,dp)
#
print("dp= ",dp)

v1:  (1, 2, -1)
x, dp :  (1, -1) -1
x, dp :  (2, 2) 3
x, dp :  (-1, 1) 2
dp=  2


# OPERATOR PRECEDENCE

In [8]:
print(8*4/2,8/4*2)
print(8+4/2,(8+4)/2,8+4*2+3)
print(8**4/2,8**(4/2))

print(0 & 0 | 1)
print(0 | 0 & 1)

16.0 4.0
10.0 6.0 19
2048.0 64.0
1
0


In [9]:
print((0 | 0) & 1)

0


# SEQUENCE COMPARISONS

In [3]:
print([5, 90, 6] < [5, 10, 80])

print([5, 90, 6] < [6, 10, 80])

print([5, 90, 6] < [5, 10])

print([5, 90, 6] < [6, 10])

print([5, 90] < [5, 10, 80])

print([5, 90] < [6, 10, 80])

False
True
False
True
False
True


In [4]:
print([5, 90] < [6, 10, 80])

True


In [5]:
print(['a', 'aa', 'b'] < ['a', 'aaa', 'b'])
print(['a', 'aaa', 'b'] < ['a', 'aa', 'b'])
print(['a', 'aa', 'b'] < ['a', 'aa'])
print(['a', 'aa'] < ['a', 'aa','b'])

True
False
False
True


In [4]:
print(['a', 'aa'] < ['a', 'aa','b'])

True


# Strings vs. Sets for Comparison

In [10]:
print('abbc' <= 'bac')
str1 = 'abbc'
str2 = 'bac'
res1 = str1 <= str2
res2 = str2 <= str1
print(res1)
print(res2)
print(str1,' comes before ', str2) if res1 else print(str2,' comes before ', str1)

set1 = {'a','b','b','c'}
set2 = {'b','a','c'}
res1 = set1 <= set2
res2 = set2 <= set1
print(res1)
print(res2)
print(set1,' is a sub-set of ', set2) if res1 else print(set2,' is a sub-set of ', set1)

set1 = {'a','b','b','c', 'x'}
set2 = {'b','a','c'}
res1 = set1 <= set2
res2 = set2 <= set1
print(res1)
print(res2)
print(set1,' is a sub-set of ', set2) if res1 else print(set2,' is a sub-set of ', set1)



True
True
False
abbc  comes before  bac
True
True
{'b', 'a', 'c'}  is a sub-set of  {'b', 'a', 'c'}
False
True
{'b', 'a', 'c'}  is a sub-set of  {'x', 'b', 'a', 'c'}


In [ ]:
set1 = {'a','b','b','c', 'x'}
set2 = {'b','a','c'}
res1 = set1 <= set2
res2 = set2 <= set1
print(res1)
print(res2)
print(set1,' is a sub-set of ', set2) if res1 else print(set2,' is a sub-set of ', set1)

# FILES

## Read & Write

In [ ]:
with open('input/TestData.csv') as file:
    print(file.read())
#

print('\n')

with open('input/TestData.csv') as file:
    print(file.read(2))
#
print('\n')

with open('input/TestData.csv') as file:
    print("move the cursor to the byte ",file.seek(3))
    print("rest of the line is ", file.readline())
#
print('\n')

with open('input/TestData.csv') as file:
    print(file.read(),"\n")
    print("move the cursor to the byte ",file.seek(0))
    print("first character: ",file.read(1))
    print("the cursor is at byte ", file.tell())
    print("move the cursor to the byte ",file.seek(3))
    print("rest of the line is ", file.readline())
    print("rest all other lines are ", file.readlines())
#
print("file.closed?: ",file.closed)

In [ ]:
with open('input/TestData.csv') as file:
    print(file.read())
#


print('\n')

with open('input/TestData.csv') as file:
    print(file.read(),"\n")
    print("move the cursor to the byte ",file.seek(0))
    print("first character: ",file.read(1))
    print("the cursor is at byte ", file.tell())
    print("move the cursor to the byte ",file.seek(3))
    print("rest of the line is ", file.readline())
    print("rest all other lines are ", file.readlines())
#
print("file.closed?: ",file.closed)

'''
with open('input/TestData.csv') as file:
    print(file.read(2))
    print(file.read(2))
    print(file.read(5))
#
print('\n')

with open('input/TestData.csv') as file:
    print("move the cursor to the byte ",file.seek(3))
    print("rest of the line is ", file.readline())
    print("rest of the line is ", file.readline())
#
print('\n')
'''

In [ ]:
with open('TestData.csv') as file:
    print(file.read(),"\n")
    print("move the cursor to the byte ",file.seek(0))
    print("first character: ",file.read(1))
    print("the cursor is at byte ", file.tell())
    print("move the cursor to the byte ",file.seek(3))
    print("rest of the line is ", file.readline())
    print("rest all other lines are ", file.readlines())
#
print("file.closed?: ",file.closed)

In [6]:
with open('INPUT/TestData_2.csv','w') as file_2:
    file_2.write("1235\n")
    print("file_2.closed?: ",file_2.closed)
    
    with open('INPUT/TestData.csv') as file_1:
        file_2.writelines(file_1.readlines())
        print("file_1.closed?: ",file_1.closed)
    #
    print("file_1.closed?: ",file_1.closed)
    print("file_2.closed?: ",file_2.closed)
#  
print("file_2.closed?: ",file_2.closed)

file_2.closed?:  False
file_1.closed?:  False
file_1.closed?:  True
file_2.closed?:  False
file_2.closed?:  True


In [ ]:
with open('TestData_2.csv') as file:
    for line in file:
        print(line, end='')
    #
#

with open('TestData_2.csv') as file:
    for line in file:
        print(line, end='\n')
    #
# 

In [7]:
with open('INPUT/TestData_2.csv') as file:
    for line in file:
        print(line, end='\n')
    #
# 

1235

x1c2y

x3b1y

d2z3y


In [25]:
with open('INPUT/TestData_2.csv') as file:
    print(file.read())
#

with open('INPUT/TestData_2.csv','rb') as file:
    i = 0
    print(i,". cursor is at ",file.tell())
    value = file.read(1)
    i +=1 
    print(i,". cursor is at ",file.tell(), value)
    while value !=b'':
        i +=1 

        value = file.read(1)
        print(i,". cursor is at ",file.tell(), value)
        
        if i == 25:
            break
    #
#

1abcd
2efg
3hjklmn
4oprs
0 . cursor is at  0
1 . cursor is at  1 b'1'
2 . cursor is at  2 b'a'
3 . cursor is at  3 b'b'
4 . cursor is at  4 b'c'
5 . cursor is at  5 b'd'
6 . cursor is at  6 b'\n'
7 . cursor is at  7 b'2'
8 . cursor is at  8 b'e'
9 . cursor is at  9 b'f'
10 . cursor is at  10 b'g'
11 . cursor is at  11 b'\n'
12 . cursor is at  12 b'3'
13 . cursor is at  13 b'h'
14 . cursor is at  14 b'j'
15 . cursor is at  15 b'k'
16 . cursor is at  16 b'l'
17 . cursor is at  17 b'm'
18 . cursor is at  18 b'n'
19 . cursor is at  19 b'\n'
20 . cursor is at  20 b'4'
21 . cursor is at  21 b'o'
22 . cursor is at  22 b'p'
23 . cursor is at  23 b'r'
24 . cursor is at  24 b's'
25 . cursor is at  24 b''


In [12]:
import io

with open('INPUT/TestData_3.csv') as file:
    print(file.read())
#
print()

with open('INPUT/TestData_3.csv','rb') as file:
    file.seek(5)
    print("1. cursor is at ",file.tell(), " after seek(5)")
    print("\tvalue for read(1): ",file.read(1))
    print("\t\tcursor is at ",file.tell(), " after read(1)")
    print()
    
    file.seek(0)
    print("2. Cursor is at ",file.tell(), " after seek(0)")
    print("\tvalue for readlines(1): ",file.readlines(1))
    print("\t\tCursor is at ",file.tell(), " after readlines(1)")
    print("\tvalue for readlines(1): ",file.readlines(1))
    print("\t\tCursor is at ",file.tell(), " after readlines(1)")
    print()
    
    file.seek(0)
    print("3. Cursor is at ",file.tell(), " after seek(0)")
    print("\tvalue for readlines(6): ",file.readlines(6))
    print("\t\tCursor is at ",file.tell())
    print("\tvalue for readlines(6): ",file.readlines(6))
    print("\t\tCursor is at ",file.tell())
    print()    
    
    #(https://docs.python.org/3.9/library/io.html?#io.IOBase.seek)
    #SEEK_CUR = 1, current stream position; offset may be negative
    file.seek(3,io.SEEK_CUR)
    print("4. cursor is at ",file.tell()," after seek(3,1)")
    print("\tvalue for read(1): ",file.read(1))
    print("\t\tCursor is at ",file.tell())
    print()
    
    #start of the stream (the default); offset should be zero or positive
    file.seek(3,io.SEEK_SET)
    print("5. cursor is at ",file.tell()," after seek(3,0)")
    print("\tvalue for readline(): ",file.readline())
    print("\t\tCursor is at ",file.tell())
    print()
#    

1abcd
2efg
3hjklmn
4oprs

1. cursor is at  5  after seek(5)
	value for read(1):  b'\n'
		cursor is at  6  after read(1)

2. Cursor is at  0  after seek(0)
	value for readlines(1):  [b'1abcd\n']
		Cursor is at  6  after readlines(1)
	value for readlines(1):  [b'2efg\n']
		Cursor is at  11  after readlines(1)

3. Cursor is at  0  after seek(0)
	value for readlines(6):  [b'1abcd\n', b'2efg\n']
		Cursor is at  11
	value for readlines(6):  [b'3hjklmn\n']
		Cursor is at  19

4. cursor is at  22  after seek(3,1)
	value for read(1):  b'r'
		Cursor is at  23

5. cursor is at  3  after seek(3,0)
	value for readline():  b'cd\n'
		Cursor is at  6



In [57]:
with open('INPUT/TestData_3.csv') as file:
    print(file.read())
#
print()

with open('INPUT/TestData_3.csv','rb') as file:
    print("value: ",file.readlines(12))

1abcd
2efg
3hjklmn
4oprs

value:  [b'1abcd\n', b'2efg\n', b'3hjklmn\n']


## Create a Folder

In [ ]:
import os

file_path = ''  #specify path
directory = ''  #specify directory
if not os.path.exists(file_path):
    try: 
        os.makedirs(directory)
    except:
        print('...') #error or warning message
    #
#

# FUNCTION

In [13]:
def my_function(x, y):
    '''Help documentation.'''
    x = x + 1 '''since x is an int it is immutable. the old x is rewritten and a new x replaced it (same name, diff int)'''
    y[0] = 'a'

    return True
#

xx, yy = 1, ['c', 3] '''List have [] and are mutable, Sets have {} and are immutable'''
print('xx: ', xx, "yy: ", yy)
print(my_function(xx, yy))
print('xx: ', xx, "yy: ", yy)

xx:  1 yy:  ['c', 3]
True
xx:  1 yy:  ['a', 3]


# CLASSES
[Doc](https://docs.python.org/3/tutorial/classes.html)

In [ ]:
#The simplest form of class definition:
'''
class ClassName:
    <statement-1>
    .
    .
    <statement-1>
'''

In [34]:
class MyClass:
    """A simple example class"""
    i = 12345
    def f(self):
        return 'hello world' 
#

#Class Instance
x = MyClass()
print(x)
print(x.f())
print(x.i)
print()

#Class Instance
print(MyClass())
print(MyClass().f())
print(MyClass().i)
print()

#Class
print(MyClass)
try:
    print(MyClass.f())
except:
    print("Error in printing MyClass.f()\n",sys.exc_info())
    print("Create an instance of the class MyClass first!")
    print("Try a different way MyClass.f(''):")
    print(MyClass.f(''))
#    
print(MyClass.i)

hello world
12345

hello world
12345

<class '__main__.MyClass'>
Error in printing MyClass.f()
 (<class 'TypeError'>, TypeError("f() missing 1 required positional argument: 'self'"), <traceback object at 0x000002599A0D6708>)
Create an instance of the class MyClass first!
Try a different way MyClass.f(''):
hello world
12345


In [17]:
class MyClass:
    """A simple example class"""
    i = 12345
    def f(self):
        
        try:
            print("i: ", self.i)
        except:
            print("Error in printing self.i\n",sys.exc_info())
        #
        
        try:
            #i = 1
            print("i: ", i,"\n")
        except:
            print("Error in printing i\n",sys.exc_info())
        #
        return 'hello world' 
    #f()
#

#Class Instance
x = MyClass()
print(x)
print(x.f())
print(x.i)
print()

#Class Instance
print(MyClass())
print(MyClass().f())
print(MyClass().i)
print()

#Class
print(MyClass)
print(MyClass.f(''))
print(MyClass.i)

i:  12345
Error in printing i
 (<class 'NameError'>, NameError("name 'i' is not defined"), <traceback object at 0x0000022A253CDEC8>)
hello world
12345

i:  12345
Error in printing i
 (<class 'NameError'>, NameError("name 'i' is not defined"), <traceback object at 0x0000022A253CDF88>)
hello world
12345

<class '__main__.MyClass'>
Error in printing self.i
 (<class 'AttributeError'>, AttributeError("'str' object has no attribute 'i'"), <traceback object at 0x0000022A252A5108>)
Error in printing i
 (<class 'NameError'>, NameError("name 'i' is not defined"), <traceback object at 0x0000022A252A5108>)
hello world
12345


<b>NOTES:</b>

x = MyClass()
creates a new instance of the class and assigns this object to the local variable x.
The instantiation operation (“calling” a class object) creates an empty object. Many classes like to create objects with instances customized to a specific initial state. Therefore a class may define a special method named \__init__(), like this:<br><br>
def \__init__(self):
>   self.data = []


In [1]:
class Complex:
    j = 1
    
    def __init__(self, realpart, imagpart):
        self.r = realpart
        self.i = imagpart
    #
        
    def print(self):
        return print(self.r,'+ j (',self.i,')')
    #
#
x = Complex(3.0, -4.5) 
x.print()



3.0 + j ( -4.5 )


In [1]:
class Complex:
    j = 1
    
    def __init__(self, realpart, imagpart):
        self.r = realpart
        self.i = imagpart
    #
        
    def print(self):
        return print(self.r,'+ j (',self.i,')')
    #
#
x = Complex(3.0, -4.5) 
x.print()

y = Complex(30.0, -40.5) 
y.print()



3.0 + j ( -4.5 )
30.0 + j ( -40.5 )


In [15]:
class NewComplex:
    x = 3.0
    _x = 2.0
    __x = 1.0    #imitation of private variable
    
    def __init__(self, realpart, imagpart):
        self.r = realpart
        self.i = imagpart
        print("In eat")
    #

    
    def m(self,x):
        print(self.x, x, self._x, self.__x)
        return True
    #


    def __m(hello,x):
        print(hello.x, x, hello._x, hello.__x)
        return False
    #
#

In [9]:
o1 = NewComplex(1, 2)

#print(o1.__x)

try:
    print("o1._NewComplex__x: ",o1._NewComplex__x)
    print("o1.__x: ",o1.__x)
except:
    print(":(")
#

In eat
o1._NewComplex__x:  1.0
:(


In [16]:
o1 = NewComplex(1, 2)
print(o1)
print(o1.r)
print(o1._x)
print(o1.x)
print(o1.m(55))
print(o1._NewComplex__m(55))

try:
    print(o1._NewComplex__x)
    print(o1.__x)
except:
    print(":(")
#

In eat
1
2.0
3.0
3.0 55 2.0 1.0
True
3.0 55 2.0 1.0
False
1.0
:(


In [26]:
class person:
    age = 0
    className = 'person'
    CLASSname = ['person']
    
    def __init__(self,pName,pAge):
        self.name = pName
        self.age = pAge
        print('a new instance is created')
    #
#

In [27]:
person_1 = person('Henry','30')
person_2 = person('Mary','25')

a new instance is created
a new instance is created


In [28]:
print('\n~~Class variable "age" and instance variable age:~~')
print([person.age,person_1.age,person_2.age])


~~Class variable "age" and instance variable age:~~
[0, '30', '25']


In [ ]:
person_1 = person('Henry','30')
person_2 = person('Mary','25')

print('\n\n~~Class variable "className" is not used in a method as an instance variable:~~')
print("Class variable: ",person.className,"\ninstance-1 variable: ",person_1.className,"\ninstance-2 variable: ",person_2.className)

print('\nClass variable "className" is updated via the class:')
person.className = 'PRSN'
print(person.className,person_1.className,person_2.className)

print('\nClass variable "className" is updated via the class:')
person.className = 'PRSN-1'
print(person.className,person_1.className,person_2.className)

print('\nClass variable "className" is updated via one of the instance objects:')
person_1.className = 'prsn-1'  #new instance attribute for person_1
print(person.className,person_1.className,person_2.className)
person_1.CLASSname = ['person-1']  #new instance attribute for person_1
print(person.CLASSname,person_1.CLASSname,person_2.CLASSname)

print('\nClass variable "className" is updated via the class:')
person.className = 'PRSN-2'
print(person.className,person_1.className,person_2.className)

print('\nClass variable "className" is updated via another instance object:')
person_2.className = 'prsn-2'  #new instance attribute for person_2
print(person.className,person_1.className,person_2.className)

print('\nClass variable "className" is updated via the class:')
person.className = 'PRSN-3'
print(person.className,person_1.className,person_2.className)

print('\n~~Class variable "name" and instance variable name:~~')
print([person.className,person_1.name,person_2.name])
print([person.age,person_1.age,person_2.age])

In [13]:
print("person.__dict__:\n ",person.__dict__)
print("\nperson_1.__dict__:\n ",person_1.__dict__)
print("\nperson_2.__dict__:\n ",person_2.__dict__)

person.__dict__:
  {'__module__': '__main__', 'age': 0, 'className': 'person', 'CLASSname': ['person'], '__init__': <function person.__init__ at 0x000001CC8AAD4CA8>, '__dict__': <attribute '__dict__' of 'person' objects>, '__weakref__': <attribute '__weakref__' of 'person' objects>, '__doc__': None}

person_1.__dict__:
  {'name': 'Henry', 'age': '30'}

person_2.__dict__:
  {'name': 'Mary', 'age': '25'}


# SCOPE
Local -> Enclosing -> Global -> Built-in<br>
[scopes-and-namespaces](https://docs.python.org/3/tutorial/classes.html?highlight=enclosing%20scope#python-scopes-and-namespaces)

In [17]:
print("Variables defined in a module is global to functions in this module.\n")

aG = 2
def f1():
    print("aG in f1: ",aG)
#
f1()

Variables defined in a module is global to functions in this module.

aG in f1:  2


In [13]:
x = 1
y = 2

def m1(y):
    print("x in m1: ",x, " is global x")
    print("x+y: ",x+y)
#

def m2(y):
    #print("x in m2: ",x)
    
    try:
        print("x in m2: ",x)
    except:
        print("x is a local variable")
    #
    
    x = 10
    print("x in m2: ",x, " is local x")
#

def m3(y):
    global x
    print("x in m3: ",x, " is global")
    x = x + 1
    print("x after modification in m3:", x)
#

print("x in main module: ",x)
print("y in main module: ",y)
print()

m1(10)
print("x in main module after m1: ",x)
print("y in main module after m1: ",y)
print()

m2(0)
print("x in main module after m2: ",x)
print("y in main module after m2: ",y)
print()

m3(0)
print("x in main module after m3: ",x)
print("y in main module after m3: ",y)

x in main module:  1
y in main module:  2

x in m1:  1  is global x
x+y:  11
x in main module after m1:  1
y in main module after m1:  2

x is a local variable
x in m2:  10  is local x
x in main module after m2:  1
y in main module after m2:  2

x in m3:  1
x in main module after m3:  2
y in main module after m3:  2


In [18]:
print("Keyword ‘global’ allows to refer a global variable inside a function\n")

aG = 2

def f1():
    global aG
    print("1.0. aG in f1: ",aG)
    aG = aG + 1
    
    def f2():
        global aG
        print("2.0. aG in f2: ",aG)
        aG = aG + 1
    #
    f2()
    print("1.1. aG in f1: ",aG)
#
f1()

Keyword ‘global’ allows to refer a global variable inside a function

1.0. aG in f1:  2
2.0. aG in f2:  3
1.1. aG in f1:  4


In [20]:
print("Keyword ‘nonlocal’ allows to refer a local variable in nested functions\n")

aG = 2

def f1():
    global aG
    aG1 = 0
        
    print("1.0. aG in f1: ",aG)
    aG = aG + 1
    
    def f2():
        nonlocal aG1
        
        print("2.0. aG1 in f2: ",aG1)
        aG1 = aG1 + 1
    #
    f2()
    print("1.1. aG in f1: ",aG)
    print("1.2. aG1 in f1: ",aG1)
#
f1()

Keyword ‘nonlocal’ allows to refer a local variable in nested functions

1.0. aG in f1:  2
2.0. aG in f2:  0
1.1. aG in f1:  3
1.2. aG1 in f1:  1


In [12]:
aG = 2

def f1():
    global aG
    bL = 1
    cL = 1
    bNL = 10
    
    print("1.0. aG in f1: ",aG)
    aG = aG + 1
    
    def f2():
        global aG
        nonlocal bNL
        
        c = 20
        
        print("2.0. aG in f2: ",aG)
        aG = aG + 1
        
        try:
            print("2.1. cL in f2: ",cL)
            print("2.1. bL in f2: ",bL)
            bL = bL + 1
        except:
            print("2.1. bL is not accessible in f2")
        #
        
        
        print("2.1. bL in f2: ",bNL)
        bNL = bNL + 1
    #
    f2()
    try:
        print("1.1. c in f1: ",c)
    except:
        print("1.1. c is not accessible in f1")
    #
    print("1.2. bL in f1: ",bL)
    print("1.3. bNL in f1: ",bNL)
    print("1.4. aG in f1: ",aG)
#
f1()

1.0. aG in f1:  2
2.0. aG in f2:  3
2.1. cL in f2:  1
2.1. bL is not accessible in f2
2.1. bL in f2:  10
1.1. c is not accessible in f1
1.2. bL in f1:  1
1.3. bNL in f1:  11
1.4. aG in f1:  4


In [23]:
xC0 = 0

class myClass:
    print("xC0 in myClass: ",xC0)

    xC1 = 'a'
    xC2 = 'b'
    
    def __init__(self,px):
        print("xC0 in __init__ : ",xC0)
        xC1 = px  #new instance xC1
        self.x = px + '_self_init'
        myClass.xC1 = px + '_MyC1_init'
    #
    
    def m(self):
        print("xC0 in m() : ",xC0)
        
        try:
            print('xC1 in m():',xC1)
        except:
            print('xC1 is not accessible')
        #
        
        try:
            print("xC2 in m(): ",xC2)
        except:
            print('xC2 is not accessible')
        #
        
        print('self.x_in_m: ', self.x)
        print('myClass.xC1_in_m: ',myClass.xC1)
        print('myClass.xC2_in_m: ',myClass.xC2)
        
        return True
    #
#

print('1~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
print("myClass.xC1: ",myClass.xC1)
print("myClass.xC2: ",myClass.xC2)
ob1 = myClass('path1')
print("ob1.xC1: ",ob1.xC1)
print("ob1.xC2: ",ob1.xC2)
print("ob1.x: ",ob1.x)
print("myClass.xC1: ",myClass.xC1)
print("myClass.xC2: ",myClass.xC2)

print("\nob1.m:.....")
ob1.m()

print('\n\n2~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
ob2 = myClass('path2')
print("ob1.xC1: ",ob1.xC1)
print("ob1.xC2: ",ob1.xC2)
print("ob1.x: ",ob1.x)
print("ob2.xC1: ",ob2.xC1)
print("ob2.xC2: ",ob2.xC2)
print("ob2.x: ",ob2.x)
print("myClass.xC1: ",myClass.xC1)
print("myClass.xC2: ",myClass.xC2)
print("\nob1.m:......")
ob1.m()
print("\nob2.m:......")
ob2.m()

print('\n\n3~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
myClass.xC = 'path3'
print("ob1.xC1: ",ob1.xC1)
print("ob1.xC2: ",ob1.xC2)
print("ob1.x: ",ob1.x)
print("ob2.xC1: ",ob2.xC1)
print("ob2.xC2: ",ob2.xC2)
print("ob2.x: ",ob2.x)
print("myClass.xC1: ",myClass.xC1)
print("myClass.xC2: ",myClass.xC2)
print("\nob1.m:......")
ob1.m()
print("\nob2.m:......")
ob2.m()

xC0 in myClass:  0
1~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
myClass.xC1:  a
myClass.xC2:  b
xC0 in __init__ :  0
ob1.xC1:  path1_MyC1_init
ob1.xC2:  b
ob1.x:  path1_self_init
myClass.xC1:  path1_MyC1_init
myClass.xC2:  b

ob1.m:.....
xC0 in m() :  0
xC1 is not accessible
xC2 is not accessible
self.x_in_m:  path1_self_init
myClass.xC1_in_m:  path1_MyC1_init
myClass.xC2_in_m:  b


2~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
xC0 in __init__ :  0
ob1.xC1:  path2_MyC1_init
ob1.xC2:  b
ob1.x:  path1_self_init
ob2.xC1:  path2_MyC1_init
ob2.xC2:  b
ob2.x:  path2_self_init
myClass.xC1:  path2_MyC1_init
myClass.xC2:  b

ob1.m:......
xC0 in m() :  0
xC1 is not accessible
xC2 is not accessible
self.x_in_m:  path1_self_init
myClass.xC1_in_m:  path2_MyC1_init
myClass.xC2_in_m:  b

ob2.m:......
xC0 in m() :  0
xC1 is not accessible
xC2 is not accessible
self.x_in_m:  path2_self_init
myClass.xC1_in_m:  path2_MyC1_init
myClass.xC2_in_m:  b


3~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ob1.xC1:  path2_MyC1_init
ob1.xC2:  b
ob1.x:  path

True

# Static Methods
[decorator](https://docs.python.org/3/glossary.html#term-decorator)<br>
[staticmethod](https://docs.python.org/3/library/functions.html?highlight=static%20method#staticmethod)<br>
[classmethod](https://docs.python.org/3/library/functions.html?highlight=static%20method#classmethod)

## Decorator

In [2]:
def decFunc(pFnc):
    x = 1
    y = 2
    print("before invoking pFnc() in decorater")
    return pFnc(x,y)
    #print("after invoking pFnc() in decorater")
#


def f1(a,b):
    sum = a+b
    print(f'Sum in f1: {sum}')
    return sum
#

def f2(a,b):
    div = a/b
    print(f'Division in f2: {div}')
    return div
#

#-------------------------------

sum = decFunc(f1)
print(f'Sum in main: {sum}')
print()
div = decFunc(f2)
print(f'Division in main: {div}')


before invoking pFnc() in decorater
Sum in f1: 3
Sum in main: 3

before invoking pFnc() in decorater
Division in f2: 0.5
Division in main: 0.5


In [4]:
def decFunc(pFnc):
    x = 1
    y = 2
    #print("before invoking pFnc() in decorater")
    output = pFnc(x,y)
    #print("after invoking pFnc() in decorater")
    return output
#

print('MAIN: BEFORE @decFunc def f11(a,b)')
@decFunc
def f11(a,b):
    sum = a+b
    #print(f'Sum in f1: {sum}')
    return sum
#

print('MAIN: AFTER @decFunc def f11(a,b)\n')
@decFunc
def f21(a,b):
    div = a/b
    #print(f'Division in f2: {div}')
    return div
#


MAIN: BEFORE @decFunc def f11(a,b)
MAIN: AFTER @decFunc def f11(a,b)



In [9]:
sum_11 = f11  #= decFunc(f11)
print(f'MAIN: Sum : {sum_11}')
print()
div_21 = f21 #= decFunc(f21)
print(f'MAIN: Division : {div_21}')

MAIN: Sum : 3

MAIN: Division : 0.5


In [8]:
def decFunc2(pFnc):
    print("BEFORE invoking wrapper in decorater")
    def wrapper(*args, **kwargs):
        print("in decorater BEFORE return")
        print(f'Sum in wrapper: {pFnc(*args, **kwargs)}')
        #return pFnc(*args, **kwargs)
    #
    print("AFTER invoking wrapper in decorater")
    return wrapper
#

@decFunc2
def f111(a,b):
    sum = a+b
    print(f'Sum in f111: {sum}')
    return sum
#

BEFORE invoking wrapper in decorater
AFTER invoking wrapper in decorater


In [111]:
sum2 = f111(2,4)  #= decFunc2(f111)
print(f'MAIN: Sum {sum2}')

in decorater BEFORE return
Sum in f111: 6
Sum in wrapper: 6
MAIN: Sum None


In [112]:
def decFunc3(pFnc):
    print("BEFORE invoking wrapper in decorater")
    def wrapper(*args, **kwargs):
        print("in decorater BEFORE return")
        print(f'Sum in wrapper: {pFnc(*args, **kwargs)}')
        return pFnc(*args, **kwargs)
    #
    print("AFTER invoking wrapper in decorater")
    return wrapper
#

@decFunc3
def f1111(a,b):
    sum = a+b
    print(f'Sum in f111: {sum}')
    return sum
#

BEFORE invoking wrapper in decorater
AFTER invoking wrapper in decorater


In [113]:
sum3 = f1111(2,4)  #= decFunc2(f1111)
print(f'MAIN: Sum {sum3}')

in decorater BEFORE return
Sum in f111: 6
Sum in wrapper: 6
Sum in f111: 6
MAIN: Sum 6


In [29]:
class C:
    varC = 1

    def __init__(self, name, age):
        self.name = name
        self.age = age
    #

    '''
    Decorator @classmethod:
       Transform a method into a class method.
       A class method receives the class as implicit first argument, just like an instance method receives the instance.
       A class method can be called either on the class (such as C.f()) or on an instance (such as C().f()).
       The instance is ignored except for its class.
       If a class method is called for a derived class, the derived class object is passed as the implied first argument.
    '''
    @classmethod #decorator
    def fCM(cls, arg1, arg2):
        
        print("cls.varC in fCM: ", cls.varC)
        
        try:
            print("varC: ", varC)
        except:
            print("varC is not accessible in fCM")
        #

        try:
            print("name: ", self.name)
        except:
            print("name of the instance is not accessible in fCM")
        #

        return cls(arg1, arg2)
    #  
        
    @staticmethod  #decorator
    def fSM(arg1, arg2):
        
        print("C.varC in fSM: ",C.varC)
        
        try:
            print("varC: ", varC)
        except:
            print("varC is not accessible in fSM")
        #

        try:
            print("name: ", self.name)
        except:
            print("name of the instance is not accessible in fSM")
        #
        
        if arg1 > arg2:          
            return (True)
        else:
            return (False)
        #
    #
    
    def __str__(self):
        return 'varC: {}, Name: {} and Age: {}'.format(self.varC, self.name, self.age)
    #
#

obj1 = C('John', 45)
print(obj1)
print()

obj2 = C.fCM('Marry', 1978) #fCM returns an instance
print(obj2)
print("obj2.name: ",obj2.name)
print()
print(obj1.fCM("Henry", 1155))
print()

print(C.fSM(45, 55))
print()

obj1.fSM(145, 155)


varC: 1, Name: John and Age: 45

cls.varC in fCM:  1
varC is not accessible in fCM
name of the instance is not accessible in fCM
varC: 1, Name: Marry and Age: 1978
obj2.name:  Marry

cls.varC in fCM:  1
varC is not accessible in fCM
name of the instance is not accessible in fCM
varC: 1, Name: Henry and Age: 1155

C.varC in fSM:  1
varC is not accessible in fSM
name of the instance is not accessible in fSM
False

C.varC in fSM:  1
varC is not accessible in fSM
name of the instance is not accessible in fSM


False

# INHERITANCE

In [ ]:
'''
class DerivedClassName(BaseClassName):
   <statement-1>
   .
   .
   <statement-N> 
'''

In [ ]:
#Multiple Inheritance
'''
class DerivedClassName(Base1, Base2, Base3):
   <statement-1>
   .
   .
   <statement-N> 
'''

In [1]:
class person:
    name = 'name'
    age = 0
    cName = 'person'
    
    def __init__(self,pName,pAge):
        self.name = pName
        self.age = pAge
    #
#

class employee(person):
    __eid = 'eid'
    department = 'dep'
    
    def __init__(self,pEid,pDep,pName,pAge):
        self.__eid = pEid
        self.department = pDep
        self.name = pName
        self.age = pAge
    #
    
    def getEid(self): return [self.__eid]
    
    def getName(self): return [self.name, employee.name, person.name]
    
    def getAge(self): return [self.age, employee.age, person.age]    
#

In [2]:
emp1 = employee(111,'CS','Mary',25)
emp2 = employee(222,'EE','Henry',30)
print("using parent class, person.name: ", person.name,", person.age: ",person.age)
print("using child class: ", employee._employee__eid,", ",employee.department,", ",employee.name,", ",employee.age)
print("using instance-1: ", emp1._employee__eid,", ",emp1.department,", ",emp1.name,", ",emp1.age)
print("using instance-2: ", emp2._employee__eid,", ",emp2.department,", ",emp2.name,", ",emp2.age)

using parent class, person.name:  name , person.age:  0
using child class:  eid ,  dep ,  name ,  0
using instance-1:  111 ,  CS ,  Mary ,  25
using instance-2:  222 ,  EE ,  Henry ,  30


In [3]:
employee.name = "NamE"
print("using parent class, person.name: ", person.name,"person.age: ",person.age)
print("using child class: ", employee._employee__eid,", ",employee.department,", ",employee.name,", ",employee.age)
print("using instance-1: ", emp1._employee__eid,", ",emp1.department,", ",emp1.name,", ",emp1.age)
print("using instance-2: ", emp2._employee__eid,", ",emp2.department,", ",emp2.name,", ",emp2.age)

using parent class, person.name:  name person.age:  0
using child class:  eid ,  dep ,  NamE ,  0
using instance-1:  111 ,  CS ,  Mary ,  25
using instance-2:  222 ,  EE ,  Henry ,  30


In [4]:
print("\n\n~~Parent updated parent class variable 'name' ~~")

person.name = "NAME"
print("using parent class, person.name: ", person.name,", person.age: ",person.age)
print("using child class: ", employee._employee__eid,", ",employee.department,", ",employee.name,", ",employee.age)
print("using instance-1: ", emp1._employee__eid,", ",emp1.department,", ",emp1.name,", ",emp1.age)
print("using instance-2: ", emp2._employee__eid,", ",emp2.department,", ",emp2.name,", ",emp2.age)



~~Parent updated parent class variable 'name' ~~
using parent class, person.name:  NAME , person.age:  0
using child class:  eid ,  dep ,  NamE ,  0
using instance-1:  111 ,  CS ,  Mary ,  25
using instance-2:  222 ,  EE ,  Henry ,  30


In [5]:
print("\n\n~~Child updated parent class variable 'name' ~~")
employee.name = "NamE"
print("using parent class, person.name: ", person.name,"person.age: ",person.age)
print("using child class: ", employee._employee__eid,", ",employee.department,", ",employee.name,", ",employee.age)
print("using instance-1: ", emp1._employee__eid,", ",emp1.department,", ",emp1.name,", ",emp1.age)
print("using instance-2: ", emp2._employee__eid,", ",emp2.department,", ",emp2.name,", ",emp2.age)



~~Child updated parent class variable 'name' ~~
using parent class, person.name:  NAME person.age:  0
using child class:  eid ,  dep ,  NamE ,  0
using instance-1:  111 ,  CS ,  Mary ,  25
using instance-2:  222 ,  EE ,  Henry ,  30


In [6]:
class person:
    name = 'name'
    age = 0
    __cName = 'person'
    
    def __init__(self,pName,pAge):
        self.name = pName
        self.age = pAge
    #
#

class employee(person):
    __eid = 'eid'
    department = 'dep'
    
    print("access to the class variable in non-local body of the class: ",__eid,", ",department)
    try:
        print([name,age]) #parent class variable
    except:
        print("Direct access to the parent class variable in non-local body of the child class is NOT available")
    #
    
    def __init__(self,pEid,pDep,pName,pAge):
        try:
            print("01. In employee __init__, eid: ",__eid)
        except:
            print("01. Direct access to a class private-variable in a method is NOT available")
        #
        
        try:
            print("02. In employee __init__02, department: ",department)
        except:
            print("02. Direct access to a class variable in a method is NOT available")
        #
        
        try:
            print("03. In employee __init__, [name, age]: ",name,age)
        except:
            print("03. Direct access to the parent class variable in a method of a child is NOT available")            
        #
        
        try:
            print("1. In employee __init__, use 'self': ",[self.__eid,self.department,self.name,self.age])
            print("Via an instance object, access to child & parent class variables in a method of the child is available")  
        except:
            print("1. Via an instance object, access to child & parent class variables in a method of the child is NOT available")  
        #
        
        self.__eid = pEid
        self.department = pDep
        self.name = pName
        self.age = pAge
        #__eid = pEid + 1
        #_employee__eid = pEid + 10
        #department = pDep + pDep
        print("\n\n~~After updating instance variables~~")
        print("21. In employee __init__: child class",[self.__eid,self.department,self.name,self.age,self._employee__eid])
        print("22. In employee __init__22, parent class's name and age: ",[person.name,person.age])
    #
    
    def getEid(self): return [self.__eid]
    
    def getName(self): return [self.name, employee.name, person.name]
    
    def getAge(self): return [self.age, employee.age, person.age]
#

    

access to the class variable in non-local body of the class:  eid ,  dep
Direct access to the parent class variable in non-local body of the child class is NOT available


In [13]:
emp1 = employee(111,'CS','Mary',25)

01. Direct access to a class private-variable in a method is NOT available
02. Direct access to a class variable in a method is NOT available
03. Direct access to the parent class variable in a method of a child is NOT available
1. In employee __init__, use 'self':  ['eid', 'dep', 'name', 0]
Via an instance object, access to child & parent class variables in a method of the child is available


~~After updating instance variables~~
21. In employee __init__: child class [111, 'CS', 'Mary', 25, 111]
22. In employee __init__22, parent class's name and age:  ['name', 0]


In [ ]:
emp1 = employee(111,'CS','Mary',25)

print("instance-1","instance-2","child class")
print(emp1._employee__eid,emp2._employee__eid,employee._employee__eid)

In [ ]:
emp1 = employee(111,'CS','Mary',25)
print("instance-1, eid: ", emp1._employee__eid)
print("child class, eid: ", employee._employee__eid)
print("instance-1, department: ", emp1.department)
print("child class, department: ",employee.department)

print("instance-1, name: ",emp1.name)
print("parent class, name: ", person.name)
print("child class, name: ", employee.name)
print("instance-1, age: ",emp1.age)
print("parent class, age: ", person.age)
print("child class, age: ", employee.age)

print("instance-1, getEid: ", emp1.getEid())
print("instance-1, getName: ", emp1.getName())
print("instance-1, getAge: ", emp1.getAge())

print('\nINSTANCE-2\n')
emp2 = employee(555,'EE','Noah',250)
print("instance-2, eid: ", emp2._employee__eid)
print("child class, eid: ", employee._employee__eid)
print("instance-2, department: ", emp2.department)
print("child class, department: ",employee.department)

print("instance-2, name: ",emp2.name)
print("parent class, name: ", person.name)
print("child class, name: ", employee.name)
print("instance-2, age: ",emp2.age)
print("parent class, age: ", person.age)
print("child class, age: ", employee.age)

print("instance-2, getEid: ", emp2.getEid())
print("instance-2, getName: ", emp2.getName())
print("instance-2, getAge: ", emp2.getAge())

# More; Classes, Functions, Models
[Data Classes](https://docs.python.org/3/library/dataclasses.html)<p>
[Built-in Functions](https://docs.python.org/3/library/functions.html?highlight=static%20method)<p>
[Data model](https://docs.python.org/3/reference/datamodel.html)<br>
[special-method-names](https://docs.python.org/3/reference/datamodel.html#special-method-names)<br>
[\__str__](https://docs.python.org/3/reference/datamodel.html#object.__str__)

# NUMERICAL CALCULATIONS

## Float & Decimal
[Decimal fixed point and floating point arithmetic](https://docs.python.org/2/library/decimal.html#module-decimal)<br>
[Float](https://docs.python.org/3.8/tutorial/floatingpoint.html)

In [1]:
from decimal import *

In [2]:
print(getcontext().prec)
d = Decimal('0.123456')

print("d= " + str(d))
for i in range(1,4):
    getcontext().prec = i
    print(str(i) + ":" + str(d * 1))
#

d1 = Decimal(22)
d2 = Decimal(7)
print("\nPrecision: ",getcontext().prec)
print("d1/d2= " + str(d1/d2))

for i in range(1,65):
    getcontext().prec = i
    print(str(i) + ":" + str(d1/d2))
#

getcontext().prec = 1030
print(str(i) + ":" + str(d1/d2))

28
d= 0.123456
1:0.1
2:0.12
3:0.123

Precision:  3
d1/d2= 3.14
1:3
2:3.1
3:3.14
4:3.143
5:3.1429
6:3.14286
7:3.142857
8:3.1428571
9:3.14285714
10:3.142857143
11:3.1428571429
12:3.14285714286
13:3.142857142857
14:3.1428571428571
15:3.14285714285714
16:3.142857142857143
17:3.1428571428571429
18:3.14285714285714286
19:3.142857142857142857
20:3.1428571428571428571
21:3.14285714285714285714
22:3.142857142857142857143
23:3.1428571428571428571429
24:3.14285714285714285714286
25:3.142857142857142857142857
26:3.1428571428571428571428571
27:3.14285714285714285714285714
28:3.142857142857142857142857143
29:3.1428571428571428571428571429
30:3.14285714285714285714285714286
31:3.142857142857142857142857142857
32:3.1428571428571428571428571428571
33:3.14285714285714285714285714285714
34:3.142857142857142857142857142857143
35:3.1428571428571428571428571428571429
36:3.14285714285714285714285714285714286
37:3.142857142857142857142857142857142857
38:3.1428571428571428571428571428571428571
39:3.14285714285

In [7]:
print("Precision: ",getcontext().prec)
print(3.14)
print("22/7.0= ",22/7.0)
print("float(22/7)= ",float(22/7))
print("22e15/7= ",22e15/7)
print("22e16/7= ",22e16/7)
print("22e17/7= ",22e17/7)
print("22e18/7",22e18/7)
print("Decimal(22/7) = ",Decimal(22/7))
print("Decimal(22/7.0)= ",Decimal(22/7.0))
print("Decimal(22) / Decimal(7) = ",Decimal(22) / Decimal(7))
print("Decimal('22') / Decimal('7')= ", Decimal('22') / Decimal('7'))

getcontext().prec = 50
print("Precision: ",getcontext().prec)
print(3.14)
print("22/7.0= ",22/7.0)
print("float(22/7)= ",float(22/7))
print("22e15/7= ",22e15/7)
print("22e16/7= ",22e16/7)
print("22e17/7= ",22e17/7)
print("22e18/7",22e18/7)
print("Decimal(22/7) = ",Decimal(22/7))
print("Decimal(22/7.0)= ",Decimal(22/7.0))
print("Decimal(22) / Decimal(7) = ",Decimal(22) / Decimal(7))
print("Decimal('22') / Decimal('7')= ", Decimal('22') / Decimal('7'))

Precision:  28
3.14
22/7.0=  3.142857142857143
float(22/7)=  3.142857142857143
22e15/7=  3142857142857143.0
22e16/7=  3.1428571428571428e+16
22e17/7=  3.142857142857143e+17
22e18/7 3.142857142857143e+18
Decimal(22/7) =  3.142857142857142793701541449991054832935333251953125
Decimal(22/7.0)=  3.142857142857142793701541449991054832935333251953125
Decimal(22) / Decimal(7) =  3.142857142857142857142857143
Decimal('22') / Decimal('7')=  3.142857142857142857142857143
Precision:  50
3.14
22/7.0=  3.142857142857143
float(22/7)=  3.142857142857143
22e15/7=  3142857142857143.0
22e16/7=  3.1428571428571428e+16
22e17/7=  3.142857142857143e+17
22e18/7 3.142857142857143e+18
Decimal(22/7) =  3.142857142857142793701541449991054832935333251953125
Decimal(22/7.0)=  3.142857142857142793701541449991054832935333251953125
Decimal(22) / Decimal(7) =  3.1428571428571428571428571428571428571428571428571
Decimal('22') / Decimal('7')=  3.1428571428571428571428571428571428571428571428571


## Machine Precision

In [78]:
x = 0
for i in range(20):
    print("i: ",i)
    x = x + 0.1
    print("\tx: ",x)
    if (x == 1):
        print("x == 1")
        break
    elif i>10:
        print("\t\ti>10")
        break
    #
#

i:  0
	x:  0.1
i:  1
	x:  0.2
i:  2
	x:  0.30000000000000004
i:  3
	x:  0.4
i:  4
	x:  0.5
i:  5
	x:  0.6
i:  6
	x:  0.7
i:  7
	x:  0.7999999999999999
i:  8
	x:  0.8999999999999999
i:  9
	x:  0.9999999999999999
i:  10
	x:  1.0999999999999999
i:  11
	x:  1.2
		i>10


In [9]:
x = 1
epsilon = 1
while x+epsilon != x:
    epsilon = epsilon/2
#

print("epsilon: ", epsilon)

epsilon:  1.1102230246251565e-16


In [10]:
x = 0
for i in range(20):
    print("i: ",i)
    x = x + 0.1
    print("\tx: ",x)
    if (abs(x-1) < epsilon):
        print("x == 1")
        break
    elif i>10:
        print("\t\ti>10")
        break
    #
#

i:  0
	x:  0.1
i:  1
	x:  0.2
i:  2
	x:  0.30000000000000004
i:  3
	x:  0.4
i:  4
	x:  0.5
i:  5
	x:  0.6
i:  6
	x:  0.7
i:  7
	x:  0.7999999999999999
i:  8
	x:  0.8999999999999999
i:  9
	x:  0.9999999999999999
i:  10
	x:  1.0999999999999999
i:  11
	x:  1.2
		i>10


In [5]:
import numpy as np 
epsilon= np.finfo(float).eps
print(epsilon)


2.220446049250313e-16


In [1]:
import math
x = 1.0
eps = 1.0
print(type(x),type(eps))

while (not x + eps == x):
    eps = eps/2.0
#
print(f"Machine Precision {2*eps}; the next max value \"2*eps\" that x + 2*eps NOT equal to x ")
print('machine precision is ', 2*eps,'; Therefore, use abs(y-x) < 2*eps instead of x==y ')

print(type(x),type(eps))

print("eps= ",eps)
y = x+eps
print("x+eps: ", y, "; x+eps == x is " , y == x, "; x+eps - x: ", y - x, "; x+eps - x <= eps is ", abs(y-x)<=eps)

yy = x+2*eps
print("x+2*eps: ", yy, "; x+2*eps == x is " , yy == x, "; x+2*eps - x: ", yy - x, "\n\t; x+2*eps - x <= eps is ", abs(yy-x)<=eps,"; x+2*eps - x <= 2*eps is ", abs(yy-x)<= 2*eps)


print("1+eps/2",1+eps/2)
print("1+ 1.5 eps",1+ eps + eps/2)
print("1+ 2 eps",1+ 2*eps)



<class 'float'> <class 'float'>
Machine Precision 2.220446049250313e-16; the next max value "2*eps" that x + 2*eps NOT equal to x 
machine precision is  2.220446049250313e-16 ; Therefore, use abs(y-x) < 2*eps instead of x==y 
<class 'float'> <class 'float'>
eps=  1.1102230246251565e-16
x+eps:  1.0 ; x+eps == x is  True ; x+eps - x:  0.0 ; x+eps - x <= eps is  True
x+2*eps:  1.0000000000000002 ; x+2*eps == x is  False ; x+2*eps - x:  2.220446049250313e-16 
	; x+2*eps - x <= eps is  False ; x+2*eps - x <= 2*eps is  True
1+eps/2 1.0
1+ 1.5 eps 1.0
1+ 2 eps 1.0000000000000002


[PEP 485 -- A Function for testing approximate equality](https://www.python.org/dev/peps/pep-0485/)

In [48]:
#Testing for approximate equality
a = 1
b = 1 + 1*eps
rel_tol = 2*eps
abs_tol = 0
print("a-b: ",a-b)
print("a==b: ",a==b)
print(abs(a-b) <= max( rel_tol * max(abs(a), abs(b)), abs_tol ))
print(math.isclose(a,b,rel_tol=rel_tol,abs_tol=abs_tol))

a-b:  0.0
a==b:  True
True
True


In [49]:
a = 1
b = 1 + 1.5*eps
rel_tol = 2*eps
abs_tol = 0
print("a-b: ",a-b)
print("a==b: ",a==b)
print(abs(a-b) <= max( rel_tol * max(abs(a), abs(b)), abs_tol ))
print(math.isclose(a,b,rel_tol=rel_tol,abs_tol=abs_tol))

a-b:  -2.220446049250313e-16
a==b:  False
True
True


In [57]:
a = 1
b = 1 + 3*eps
rel_tol = 2*eps
abs_tol = 0
print("a-b: ",a-b)
print("a==b: ",a==b)
print(abs(a-b) <= max( rel_tol * max(abs(a), abs(b)), abs_tol ))
print(math.isclose(a,b,rel_tol=rel_tol,abs_tol=abs_tol))

a-b:  -4.440892098500626e-16
a==b:  False
False
False


## Round of Error

"Some decimal numbers can't be represented exactly in binary, resulting in small roundoff errors. So we need a decimal data type that represents exactly decimal numbers. Instead of a binary data type, we need a decimal one."
[Decimal](https://www.python.org/dev/peps/pep-0327/#abstract)

In [14]:
print("1:")
print("0.1 + 0.1 + 0.1 - 0.3 =\t" + str(0.1 + 0.1 + 0.1 - 0.3 ) )
print("Decimal Arithmetic:\t" + str(Decimal(0.1) + Decimal(0.1) + Decimal(0.1) - Decimal(0.3) ) )
print("0.1 + 0.1 + 0.1 == 0.3: ", 0.1 + 0.1 + 0.1 == 0.3)
print("1 + 1 + 1 == 3: ",1 + 1 + 1 == 3)
print("0.1e55 + 0.1e55 + 0.1e55 == 0.3e55: ",0.1e55 + 0.1e55 + 0.1e55 == 0.3e55)

#https://docs.python.org/3/tutorial/floatingpoint.html?highlight=float

print("\n2:")
print("0.1 is printed as ",0.1)
print("format(0.1, '.55f'): ",format(0.1, '.55f'))
print("Decimal(0.1): ",Decimal(0.1))
print("format(0.1, '.56f')",format(0.1, '.56f'))
print("Decimal(3602879701896397 / 2 ** 55): ",Decimal(3602879701896397 / 2 ** 55) )
print("(0.1).as_integer_ratio(): ",(0.1).as_integer_ratio())
print("0.1e55: ",0.1e55)

print("\n3:")
print("0.1 + 0.1: ",0.1 + 0.1)
print("Decimal(0.1) + Decimal(0.1): ",Decimal(0.1) + Decimal(0.1))

print("\n4:")
print("(1 + 1 + 1 - 3) /10: ", (1 + 1 + 1 - 3) /10 )
print( (Decimal(1) + Decimal(1) + Decimal(1) - Decimal(3)) / Decimal(10) )

1:
0.1 + 0.1 + 0.1 - 0.3 =	5.551115123125783e-17
Decimal Arithmetic:	2.775557561565156540423631668E-17
0.1 + 0.1 + 0.1 == 0.3:  False
1 + 1 + 1 == 3:  True
0.1e55 + 0.1e55 + 0.1e55 == 0.3e55:  False

2:
0.1 is printed as  0.1
format(0.1, '.55f'):  0.1000000000000000055511151231257827021181583404541015625
Decimal(0.1):  0.1000000000000000055511151231257827021181583404541015625
format(0.1, '.56f') 0.10000000000000000555111512312578270211815834045410156250
Decimal(3602879701896397 / 2 ** 55):  0.1000000000000000055511151231257827021181583404541015625
(0.1).as_integer_ratio():  (3602879701896397, 36028797018963968)
0.1e55:  1e+54

3:
0.1 + 0.1:  0.2
Decimal(0.1) + Decimal(0.1):  0.2000000000000000111022302463

4:
(1 + 1 + 1 - 3) /10:  0.0
0


In [2]:
print("format(0.1, '.55f'): ",format(1/10, '.55f'))

format(0.1, '.55f'):  0.1000000000000000055511151231257827021181583404541015625


## Time out the Code

In [15]:
import time
import numpy as np

M = 32
N = 64
xmin = ymin = 0.0
xmax = ymax = 1.0

x = np.linspace(xmin, xmax, M, endpoint=False)
y = np.linspace(ymin, ymax, N, endpoint=False)

t0 = time.time()

g = np.zeros((M, N))

for i in range(M):
    for j in range(N):
        g[i,j] = np.sin(2.0*np.pi*x[i]*y[j])
        
t1 = time.time()
print("time elapsed: {} s".format(t1-t0))

time elapsed: 0.004986286163330078 s


# Copy Operations

"A <font color='red'><b>shallow copy</b></font> creates a new <font color='blue'>*view*</font> into the array -- the data is the same, but the array properties can be different.

Since the *underlying* data is in the same memory, changing an element of one is <b>reflected in the other</b>.

Even slices into an array are just views, still pointing to the <b>same *base*</b> memory."<p>
    
"The difference between shallow and deep copying is only relevant for <b>compound objects</b> (objects that contain other objects, like lists or class instances):

A shallow copy constructs a new compound object and then (to the extent possible) inserts references into it to the objects found in the original.

A deep copy constructs a new compound object and then, recursively, inserts copies into it of the objects found in the original."<p>

[Copy](https://docs.python.org/3/library/copy.html)


In [1]:
import numpy as np

a0 = np.arange(15)
c0 = a0
a1 = a0.reshape(3,5)
b0 = a1[:]

print("ao:"), print(a0)

print("\nco:"), print(c0)

print("\n........... c0= a0 .... a1= reshape of a0  ..... b0= a1[:] ......")
print("a1:"), print(a1), print("\nbo (a1[:]) :")

print(b0)

ao:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

co:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

........... c0= a0 .... a1= reshape of a0  ..... b0= a1[:] ......
a1:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

bo (a1[:]) :
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [2]:
print('\n..... Sharing references .... c0= a0 .... a1= reshape of a0  ..... b0= a1[:] ......')
print("a0 points ", "directly to the same meory where c0 points" if a0 is c0 else 'different')
print("ID of a0: " + str(id(a0))), print("ID of c0: " + str(id(c0)))

print("\na0 points ", "directly to the same meory where a1 points" if a0 is a1 else "different memory where a1 points")
print("a1 points ", "directly to the same meory where b0 points" if a1 is b0 else "different memory where b0 points")
print("b0 points ", "directly to the same meory where a1 points" if b0 is a1 else "different memory where a1 points")

print("\nID of a1: " + str(id(a1)))
print("ID of b0: " + str(id(b0)))


..... Sharing references .... c0= a0 .... a1= reshape of a0  ..... b0= a1[:] ......
a0 points  directly to the same meory where c0 points
ID of a0: 2539283132944
ID of c0: 2539283132944

a0 points  different memory where a1 points
a1 points  different memory where b0 points
b0 points  different memory where a1 points

ID of a1: 2539283133504
ID of b0: 2539283134144


In [2]:
print("\n........... c0= a0 .... a1= reshape of a0  ..... b0= a1[:] ...... ")

print("\na1[1,1] = 111"); a1[1,1] = 111

print("\na1:"), print(a1)

print("\nbo:"), print(b0)

print("\na0:"), print(a0)

print("\nco:"), print(c0);


........... c0= a0 .... a1= reshape of a0  ..... b0= a1[:] ...... 

a1[1,1] = 111

a1:
[[  0   1   2   3   4]
 [  5 111   7   8   9]
 [ 10  11  12  13  14]]

bo:
[[  0   1   2   3   4]
 [  5 111   7   8   9]
 [ 10  11  12  13  14]]

a0:
[  0   1   2   3   4   5 111   7   8   9  10  11  12  13  14]

co:
[  0   1   2   3   4   5 111   7   8   9  10  11  12  13  14]


In [3]:
print("\n........... c0= a0 .... a1= reshape of a0  ..... b0= a1[:] ...... a1[1,1] = 222 ...... ")
b1 = b0[1:3,1:3] #slicing

print("\nb1 = b0[1:3,1:3]")
print("\nb1:"), print(b1),

a1[1,1] = 222
print("\na1[1,1] = 222")

print("\na1:"), print(a1)

print("\nbo:"), print(b0)

print("\nb1:"), print(b1)

print("\na0:"), print(a0)

print("\nco:"), print(c0);


........... c0= a0 .... a1= reshape of a0  ..... b0= a1[:] ...... a1[1,1] = 222 ...... 

b1 = b0[1:3,1:3]

b1:
[[111   7]
 [ 11  12]]

a1[1,1] = 222

a1:
[[  0   1   2   3   4]
 [  5 222   7   8   9]
 [ 10  11  12  13  14]]

bo:
[[  0   1   2   3   4]
 [  5 222   7   8   9]
 [ 10  11  12  13  14]]

b1:
[[222   7]
 [ 11  12]]

a0:
[  0   1   2   3   4   5 222   7   8   9  10  11  12  13  14]

co:
[  0   1   2   3   4   5 222   7   8   9  10  11  12  13  14]


In [4]:
print("\n........... c0= a0 .... a1= reshape of a0  ..... b0= a1[:] .......... a1[1,1] = 333")

b2 = b0.copy()
print("\nb2 copy of b0:"), print(b2)
print("\n..... {b2} --> R2.......")

a1[1,1] = 333; print("\na1[1,1] = 333")

print("\na1:"), print(a1)
print("\nbo:"), print(b0)
print("\nb1:"), print(b1)
print("\na0:"), print(a0)
print("\nco:"), print(c0);

print("\nb2 copy of b0:"), print(b2)

b0[1,1] = 666; print("\nb0[1,1] = 666")
print("\nbo:"), print(b0)
print("\nb2 copy of b0:"), print(b2)

print("\na1:"), print(a1),

print("\nbo:"), print(b0)

print("\nb1:"), print(b1)

print("\na0:"), print(a0)

print("\nco:"), print(c0);


........... c0= a0 .... a1= reshape of a0  ..... b0= a1[:] .......... a1[1,1] = 333

b2 copy of b0:
[[  0   1   2   3   4]
 [  5 222   7   8   9]
 [ 10  11  12  13  14]]

..... {b2} --> R2.......

a1[1,1] = 333

a1:
[[  0   1   2   3   4]
 [  5 333   7   8   9]
 [ 10  11  12  13  14]]

bo:
[[  0   1   2   3   4]
 [  5 333   7   8   9]
 [ 10  11  12  13  14]]

b1:
[[333   7]
 [ 11  12]]

a0:
[  0   1   2   3   4   5 333   7   8   9  10  11  12  13  14]

co:
[  0   1   2   3   4   5 333   7   8   9  10  11  12  13  14]

b2 copy of b0:
[[  0   1   2   3   4]
 [  5 222   7   8   9]
 [ 10  11  12  13  14]]

b0[1,1] = 666

bo:
[[  0   1   2   3   4]
 [  5 666   7   8   9]
 [ 10  11  12  13  14]]

b2 copy of b0:
[[  0   1   2   3   4]
 [  5 222   7   8   9]
 [ 10  11  12  13  14]]

a1:
[[  0   1   2   3   4]
 [  5 666   7   8   9]
 [ 10  11  12  13  14]]

bo:
[[  0   1   2   3   4]
 [  5 666   7   8   9]
 [ 10  11  12  13  14]]

b1:
[[666   7]
 [ 11  12]]

a0:
[  0   1   2   3   4   5 666   

In [6]:
import copy

b3 = copy.copy(b0)

print("\nb3 copy of b0:"), print(b3)
print("\n..... {b3} --> ???.......")

a1[1,1] = 777; print("\na1[1,1] = 777")

print("\nbo:"), print(b0)
print("\nb3 copy of b0:"), print(b3)

b0[1,1] = 888; print("\nb0[1,1] = 888")
print("\nb3 copy of b0:"), print(b3)
print("\na1:"), print(a1),
print("\nbo:"), print(b0)
print("\nb1:"), print(b1)
print("\na0:"), print(a0)
print("\nco:"), print(c0)
print("\nb2:"), print(b2);


b3 copy of b0:
[[  0   1   2   3   4]
 [  5 666   7   8   9]
 [ 10  11  12  13  14]]

..... {b3} --> ???.......

a1[1,1] = 777

bo:
[[  0   1   2   3   4]
 [  5 777   7   8   9]
 [ 10  11  12  13  14]]

b3 copy of b0:
[[  0   1   2   3   4]
 [  5 666   7   8   9]
 [ 10  11  12  13  14]]

b0[1,1] = 888

b3 copy of b0:
[[  0   1   2   3   4]
 [  5 666   7   8   9]
 [ 10  11  12  13  14]]

a1:
[[  0   1   2   3   4]
 [  5 888   7   8   9]
 [ 10  11  12  13  14]]

bo:
[[  0   1   2   3   4]
 [  5 888   7   8   9]
 [ 10  11  12  13  14]]

b1:
[[888   7]
 [ 11  12]]

a0:
[  0   1   2   3   4   5 888   7   8   9  10  11  12  13  14]

co:
[  0   1   2   3   4   5 888   7   8   9  10  11  12  13  14]

b2:
[[  0   1   2   3   4]
 [  5 222   7   8   9]
 [ 10  11  12  13  14]]


In [7]:
L1 = [1, 2, [3,5], 4]
L21 = L1.copy()

print('...... Originals ....... ')
print("L1:\n",L1)
print("L21:\n",L21)

L21[1] = 3
L21[2][0] = 7

print('\n...... L21 = [1, 3, [7,5], 4]  .......  ')
print()
print("L1:\n",L1)
print("L21:\n",L21)

L1[1] = 8
L1[2][0] = 0

print('\n...... L1 = [1, 8, [0,5], 4]  .......  ')
print("L1:\n",L1)
print("L21:\n",L21)

...... Originals ....... 
L1:
 [1, 2, [3, 5], 4]
L21:
 [1, 2, [3, 5], 4]

...... L21 = [1, 3, [7,5], 4]  .......  

L1:
 [1, 2, [7, 5], 4]
L21:
 [1, 3, [7, 5], 4]

...... L1 = [1, 8, [0,5], 4]  .......  
L1:
 [1, 8, [0, 5], 4]
L21:
 [1, 3, [0, 5], 4]


In [8]:
L1 = [1, 2, [3,5], 4]
L20 = L1.copy()
L21 = copy.copy(L1)
L22 = copy.deepcopy(L1)

print('...... Originals ....... ')
print("L1:\n",L1)
print("L20:\n",L20)
print("L21:\n",L21)
print("L22:\n",L22)

L21[1] = 3
L21[2][0] = 7
L22[2][0] = 9

print('\n...... L21 = [1, 3, [7,5], 4]  ....... L22 = [1, 2, [9,5], 4] ')
print()
print("L1:\n",L1)
print("L20:\n",L20)
print("L21:\n",L21)
print("L22:\n",L22)

L1[1] = 8
L1[2][0] = 0

print('\n...... L1 = [1, 8, [0,5], 4]  .......  ')
print("L1:\n",L1)
print("L20:\n",L20)
print("L21:\n",L21)
print("L22:\n",L22)

...... Originals ....... 
L1:
 [1, 2, [3, 5], 4]
L20:
 [1, 2, [3, 5], 4]
L21:
 [1, 2, [3, 5], 4]
L22:
 [1, 2, [3, 5], 4]

...... L21 = [1, 3, [7,5], 4]  ....... L22 = [1, 2, [9,5], 4] 

L1:
 [1, 2, [7, 5], 4]
L20:
 [1, 2, [7, 5], 4]
L21:
 [1, 3, [7, 5], 4]
L22:
 [1, 2, [9, 5], 4]

...... L1 = [1, 8, [0,5], 4]  .......  
L1:
 [1, 8, [0, 5], 4]
L20:
 [1, 2, [0, 5], 4]
L21:
 [1, 3, [0, 5], 4]
L22:
 [1, 2, [9, 5], 4]


In [9]:
L3 = [1, 2, 3, 4]
L4 = copy.deepcopy(L3)

print("L3:\n",L3)
print("L4:\n",L4)

L3[2] = 8
print("\nL3[2] = 8:")
print("L3:\n",L3)
print("L4:\n",L4)


L4[2] = 7
print("\nL4[2] = 7:")
print("L3:\n",L3)
print("L4:\n",L4)

L3:
 [1, 2, 3, 4]
L4:
 [1, 2, 3, 4]

L3[2] = 8:
L3:
 [1, 2, 8, 4]
L4:
 [1, 2, 3, 4]

L4[2] = 7:
L3:
 [1, 2, 8, 4]
L4:
 [1, 2, 7, 4]
